name: Build and Zip
on: push
jobs:
  cli:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node version
        run: node -v

      - name: Zip
        env:
          PLUGIN_MACHINE_TOKEN: ${{ secrets.PLUGIN_MACHINE_TOKEN }}
        run: |
          npx plugin-machine plugin build --token="$env:PLUGIN_MACHINE_TOKEN"
          npx plugin-machine plugin zip --token="$env:PLUGIN_MACHINE_TOKEN"
          npx plugin-machine upload --token="$env:PLUGIN_MACHINE_TOKEN"
  action:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node version
        run: node -v

      - name: Zip
        uses: imaginarymachines/builder-action@831a90413d3a1032c73675813e57f4048b0d6b37
        with:
          token:  ${{ secrets.PLUGIN_MACHINE_TOKEN }}
          pluginDir: ${{ github.workspace }}

          
