name: Build and Zip
on: push
jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node version
        run: node -v

      - name: Zip
        env:
          PLUGIN_MACHINE_TOKEN: ${{ secrets.PLUGIN_MACHINE_TOKEN }}
        run: |
          npx plugin-machine plugin build --token="$env:PLUGIN_MACHINE_TOKEN"
          npx plugin-machine plugin zip --token="$env:PLUGIN_MACHINE_TOKEN"

      - name: 'Upload ZIP'
        uses: actions/upload-artifact@v2
        with:
          name: action-test.zip
          path: action-test.zip
