name: Build and Zip
on: push
jobs:

  action:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node version
        run: node -v

      - name: Zip
        id: plugin-machine
        uses: imaginarymachines/builder-action@831a90413d3a1032c73675813e57f4048b0d6b37
        with:
          token:  ${{ secrets.PLUGIN_MACHINE_TOKEN }}
          pluginDir: ${{ github.workspace }}
      - name: comment
        run: echo ${{steps.pluginmachine.outputs.upload}}
  
